{% set name = "scif" %}
{% set version = "0.0.84" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4b35063c696400467ff8b393705fbe72d01d9b6bcd2200a08d3b2c8a71563e53

build:
  number: 1
  entry_points:
    - scif=scif.client:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: true

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - pygments >=2.1.3
    - six >=1.7.0

test:
  imports:
    - scif
    - scif.client
    - scif.client.dump
    - scif.client.help
    - scif.client.execute
    - scif.client.inspect
    - scif.client.install
    - scif.client.list
    - scif.client.preview
    - scif.client.pyshell
    - scif.client.run
    - scif.client.shell
    - scif.client.test
    - scif.client.utils
    - scif.defaults
    - scif.logger
    - scif.logger.message
    - scif.logger.spinner
    - scif.logger.progress
    - scif.main
    - scif.main.apps
    - scif.main.base
    - scif.main.commands
    - scif.main.environment
    - scif.main.helpers
    - scif.main.install
    - scif.main.parser
    - scif.main.preview
    - scif.main.setup
    - scif.utils
    - scif.utils.fileio
    - scif.utils.terminal
    - scif.tests
    - scif.version
  commands:
    - scif --help

about:
  home: https://www.github.com/vsoch/scif
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: a filesystem organization for scientific software and metadata
  doc_url: https://sci-f.github.io
  dev_url: https://github.com/vsoch/scif

extra:
  recipe-maintainers:
    - vsoch
